#!/bin/bash

## Copyright (C) 2021 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose

if [ "$(id -u)" != "0" ]; then
   printf '%s\n' "ERROR: must be run as root! sudo $0"
   exit 1
fi

sed -i '/OnlyShowIn/d' /etc/xdg/autostart/orca-autostart.desktop

printf '%s\n' "OK"
